WIP: Create testing.md
UKHomeOffice/engineering-guidance-and-standards pull request #320
Opened 2023-10-26 12:27 UTC by aaronrussellHO

Is this pull request a content or a code change?

# Code change
I can confirm:
## Accessibility considerations
- [X] Please review the [accessibility checks for layout changes](https://github.com/UKHomeOffice/engineering-guidance-and-standards/blob/main/technical-docs/accessibility/layout-checks.md).

- [X] This change will not change layouts, page structures or anything else that might impact accessibility

# Content change 
- [X] Please review the [accessibility checks for content changes](https://github.com/UKHomeOffice/engineering-guidance-and-standards/blob/main/technical-docs/accessibility/content-checks.md).

I can confirm:
- [X] Content does not include any code or configuration changes (excluding frontmatter information)
- [ ] Content meets the content standards
e.g. [Writing a principle](https://engineering.homeoffice.gov.uk/standards/writing-a-principle/) and [Writing a standard](https://engineering.homeoffice.gov.uk/standards/writing-a-standard/)
- [X] Content is suitable to open source, i.e.:
    - Content does not relate to unreleased gov policy
    - Content does not refer to anti-fraud mechanisms
    - Content does not include sensitive business logic
- [X] Last updated date for content is correct

2023-11-23 15:20 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Test coverage helps a team understand the amount of code that is tested within a codebase. Setting a minimum threshold (such as 80%) ensures that any new code is tested. Coverage is not always accura
```suggestion
### You MUST have a way of measuring the effectiveness of testing 

Test coverage helps a team understand the amount of code that is tested within a codebase. Setting a minimum threshold (such as 80%) ensures that any new code is tested. Coverage is not always accurate, as if a test has an always truthy assertion then coverage can over estimate. However, it is a good indication overall.
```

2023-11-23 15:20 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Test coverage helps a team understand the amount of code that is tested within a codebase. Setting a minimum threshold (such as 80%) ensures that any new code is tested. Coverage is not always accura
Test early and often

2023-11-23 15:25 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Test coverage helps a team understand the amount of code that is tested within a codebase. Setting a minimum threshold (such as 80%) ensures that any new code is tested. Coverage is not always accura
Add something around track past data

2023-11-23 15:25 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Testing security issues in your pipeline is vital to help make sure your application is secure and doesn't have any vulnerabilities.
Code smells etc.

2023-11-23 15:36 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Test coverage helps a team understand the amount of code that is tested within a codebase. Setting a minimum threshold (such as 80%) ensures that any new code is tested. Coverage is not always accura
Other examples e.g. mutation testing.

2023-11-23 15:41 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Understanding why tests are failing and been transparent about why (such as a report, or CI pipeline) can help the whole team see the value, and understand where failures are occuring. It also builds
When a pipeline fails, should be able to see what has failed,

2023-11-23 15:46 UTC, aaronrussellHO commented on docs/standards/testing.md
> +The intent of any test should be clear as they can provide as a form of documentation to the overall solution, they should be relatively easy to understand with coverage tracked, though this must be
Should include that it's a programmatic tests.

2023-11-23 15:54 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Understanding why tests are failing and been transparent about why (such as a report, or CI pipeline) can help the whole team see the value, and understand where failures are occuring. It also builds
```suggestion
### It MUST be clear what test results are.

Understanding why tests are failing and been transparent about why (such as a report, or CI pipeline) can help the whole team see the value, and understand where failures are occurring. It also builds confidence within the team and business when tests wither catch something, or that they are running regularly. You shouldn't need to check manually whether a test has passed or failed.
```

2023-11-23 15:55 UTC, aaronrussellHO commented on docs/standards/testing.md
> +
Add something about making sure tests can fail

2023-11-23 15:57 UTC, aaronrussellHO commented on docs/standards/testing.md
> +
Mutation tests can help with this.

2023-11-23 16:03 UTC, aaronrussellHO commented on docs/standards/testing.md
> +A developer should be able to run tests quickly to help understand the inpact of change. The longer it takes for a suite of tests to run, the less likely a developer is going to run the entire suite,
Main reason is to build confidence.
```suggestion
### Tests MUST complete in a reasonable time

A developer should be able to run tests quickly to help understand the impact of change. The longer it takes for a suite of tests to run, the less likely a developer is going to run the entire suite, which might cause issues later on in the development cycle.
```

2023-11-23 16:38 UTC, deanwhitehouseHO commented on docs/standards/testing.md
> +---
Do we need something like (but a lot more eloquent and succint)

## Tests should be considered failing or in need of review if they demonstrate a significant change in execution time when a code change is made

Maybe `Tests MUST be treated as failed on Unintended Performance Deviations`

2023-11-27 16:47 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +Testing code forms part of the core of developing code. Testing should provide confidence to stakeholders and be proportionate to risk.
Confidence of what?

If the team is responsible for the production service, is this about external stakeholders or is it about the team themselves knowing whether a change is safe?

2023-11-27 16:48 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +The intent of any test should be clear as they can provide as a form of documentation to the overall solution, they should be relatively easy to understand with coverage tracked, though this must be
```suggestion
The intent of any test should be clear as they can provide a form of documentation to the overall solution, they should be relatively easy to understand with coverage tracked, although it must be stressed that coverage is not the be all end all.
```

2023-11-27 16:57 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +Testing for all eventualities helps to write code that can handle errors in a better way. This should include things like testing for illegal arguements, or no arguements to be passed.
I think that there is a problem here in that there can be many unhappy paths.

I would go for something like this:
- MUST test the happy path
- MUST test security features (e.g. ensure data can't be seen when not logged in)
- SHOULD test common unhappy paths

As with all of this there's also the question of what is proportionate and at what time in a project's life-cycle.

2023-11-27 17:00 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +A developer should be able to run tests quickly to help understand the inpact of change. The longer it takes for a suite of tests to run, the less likely a developer is going to run the entire suite,
I think this statement is a bit too strong.

We need automated tests that run as a part of the overall pipeline, of getting a change out to production, to be fast. (And what counts as fast probably depends on the complexity of the project and the appetite for risk.)

That said, I think there's probably still a case for longer running tests that do NOT block deployments, but instead alert the team whenever they fail. i.e. Changes don't wait for them, but if they fail that causes an incident that must be addressed by the team.

Soak tests would fall into this category, for example.

2023-11-27 17:03 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +Testing security issues in your pipeline is vital to help make sure your application is secure and doesn't have any vulnerabilities.
I think we should be making use of automated security testing, but the above statement is untrue. - It is possible to write secure software without such testing.

I think it's also important that we avoid teams having a false sense of security about such testing. - They can only catch some of the obvious things. We still need good peer review, and we still need developers to think about security and what could go wrong.

2023-11-27 17:04 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +
That's normally called red/green testing I think.
Obviously it comes for free with TDD.

2023-11-27 17:05 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +---
This would be nice, but can we currently do it across the board?

If not, I don't think it's right to have it as a MUST.

2023-11-27 17:07 UTC, daniel-ac-martin commented
I think it would be good to call out a few things (possibly in the introduction):
- That testing should be automated, where possible
- That tests should NOT be silo'd to QAT and that developers should be able to iterate on the tests

2023-11-28 08:35 UTC, aaronrussellHO commented on docs/standards/testing.md
> +A developer should be able to run tests quickly to help understand the inpact of change. The longer it takes for a suite of tests to run, the less likely a developer is going to run the entire suite,
@daniel-ac-martin Yeah, we spoke about this, and said this applies more to unit/integration tests, as there are other types of testing that can take longer. I wonder if we can word it differently?

2023-11-28 08:40 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Testing code forms part of the core of developing code. Testing should provide confidence to stakeholders and be proportionate to risk.
@daniel-ac-martin this was for example, to show a PO that changes are not going to break things, as we have tests in place to help cover it.

2023-11-28 08:41 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Testing for all eventualities helps to write code that can handle errors in a better way. This should include things like testing for illegal arguements, or no arguements to be passed.
Why is it only a SHOULD that we test unhappy paths? Arguably, these would be more important?

2023-11-28 08:42 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Testing security issues in your pipeline is vital to help make sure your application is secure and doesn't have any vulnerabilities.
@daniel-ac-martin agreed, I will look at rephrasing this

2023-11-28 16:01 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +---
Hmm. I think this is partially related to the guidance vs standards question.

I've already got a lot of the guidance that I think I need for my area, so I'm mainly looking for a set of formal standards to assess projects against.

But there is a strong case to be made for trying to bring them together. I think that would be a question of how we present that.

As for more aspirational ideas ("Wouldn't it be nice if") that potentially could like alongside guidance, alternatively it could be something that we track in issues against this repo.

2023-11-29 14:14 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +Testing code forms part of the core of developing code. Testing should provide confidence to stakeholders and be proportionate to risk.
With regards to 'confidence', I think it's about gaining assurance that the software/service still correctly performs the functions that it needs to. i.e. That it is 'safe' to deploy the change.

With regards to stakeholders, I think I would avoid the term, as it can be misinterpreted. Basically, the key thing is that we need to aim for this sort of assurance to sit with the product team. I don't even think that a PO should need to worry about this if he/she has faith the the developers. The assurance is really for the developers themselves, as they are the ones that are responsible for the production service.

I think I'd go for _something_ like:
> Testing your changes is necessary to gain assurance that they can be deployed safely to production and that the service will still function as expected.

2023-11-29 14:21 UTC, daniel-ac-martin commented on docs/standards/testing.md
> +Testing for all eventualities helps to write code that can handle errors in a better way. This should include things like testing for illegal arguements, or no arguements to be passed.
We might be running into semantics here, and what counts as an unhappy path. The main thing I'm worried about is fractal complexity as there can be many more unhappy paths than happy ones. (Consider form validation, there might be one valid way through but each field might have many different ways to be invalid.)

I do think it's important to test the more common unhappy paths.

But if I had a service that is very early in its life-cycle (and subject to rapid change), I would be more worried about maintaining the happy path than whether things go wrong in the correct way. (The big exception being security features.)

2023-11-29 14:23 UTC, daniel-ac-martin commented
Oh, do we also want to call out automated accessibility testing here? (Same issue as with security testing in that it can't catch everything.)

2023-12-07 09:28 UTC, aaronrussellHO commented on docs/standards/testing.md
> +Testing for all eventualities helps to write code that can handle errors in a better way. This should include things like testing for illegal arguements, or no arguements to be passed.
I'm going to take these suggestions to the next SD guild meeting and discuss them further and get the opinions of the group.

2023-12-07 15:16 UTC, aaronrussellHO commented on docs/standards/testing.md
> +You need to know ehether your test effictiveness has changed over the course of your developments and that you haven't had any regressions on your changes. Tracking this effectiveness over times help
```suggestion
You need to know whether your test effectiveness has changed over the course of your developments and that you haven't had any regressions on your changes. Tracking this effectiveness over time helps to understand the landscape of your testing moving forward.
```

2023-12-07 15:17 UTC, aaronrussellHO commented on docs/standards/testing.md
> +One way of doing this is through monitoring test coverage, Test coverage helps a team understand the amount of code that is tested within a codebase. Setting a minimum threshold (such as 80%) ensures
```suggestion
One way of doing this is through monitoring test coverage, test coverage helps a team understand the amount of code that is tested within a codebase. Setting a minimum threshold (such as 80%) ensures that any new code is tested. Another example is mutation testing.
```

2023-12-07 15:19 UTC, robertdeniszczyc2 commented on docs/standards/testing.md
> +Accessibility testing can help understand where any accessibility issuses may be in your code. If there is a failure, it shouldblock your code from deploying so you have opportunity to fix any issues
```suggestion
Accessibility testing can help understand where any accessibility issues may be in your code. If there is a failure, it should block your code from deploying so you have opportunity to fix any issues first.
```

2023-12-07 15:20 UTC, robertdeniszczyc2 commented on docs/standards/testing.md
> +Accessibility testing can help understand where any accessibility issuses may be in your code. If there is a failure, it shouldblock your code from deploying so you have opportunity to fix any issues
Should this completely block deployments?

2023-12-07 16:05 UTC, aaronrussellHO commented on docs/standards/testing.md
> +- [You MUST make sure tests fail](#you-must-make-sure-tests-fail)
```suggestion
- [You MUST test early and often](#you-must-test-early-and-often)
- [You MUST automate tests]
- [Tests MUST be repeatable](#tests-must-be-repeatable)
- [You MUST have a way of measuring the effectiveness of testing](#you-must-have-a-way-of-measuring-the-effectiveness-of-testing)
- [It MUST be clear what is being tested and what the results are](#it-must-be-clear-what-is-being-tested-and-what-the-results-are)
- [Tests MUST think about the edge cases](#tests-must-be-included-for-both-the-happy-path-and-unhappy-path)
```

Add a pattern for what makes a test repeatable.
Call out security testing in automated testing.
Avoid false positives pattern.

2023-12-21 15:34 UTC, aaronrussellHO commented on docs/standards/testing.md
> +An example is through making sure piplelines fail when tests fail, and you're able to see more information about why.
```suggestion
### Tests MUST have a purpose and explicit result

Tests must indicate why they are failing, showing expected and actual responses and the method under test.

An example is through making sure pipelines fail when tests fail, and you're able to see more information about why.
```

2023-12-21 15:42 UTC, aaronrussellHO commented on docs/standards/testing.md
> +- [You MUST make it clear what is being tested and what the results are](#you-must-make-it-clear-what-is-being-tested-and-what-the-results-are)
```suggestion
- [Tests MUST have a purpose and explicit result](#tests-must-have-a-purpose-and-explicit-result)
```

2024-01-04 16:35 UTC, jeff-horton-ho-sas commented on docs/standards/testing.md
> +Automating tests enabled the tests to be ran often, and block pipelines that fail testing. It also means code is tested often, making sure that everything is working as expected.
```suggestion
Automating tests enables the tests to be run consistently and often. Automated tests can be run as part of a build pipeline, and block the pipeline if they fail. It also means code is tested often, making sure that everything is working as expected.
```

2024-01-04 16:35 UTC, jeff-horton-ho-sas commented on docs/standards/testing.md
> +
```suggestion
### Tests MUST have a purpose and explicit result

Tests must indicate why they are failing, showing expected and actual responses and the name of the test.

An example is through making sure pipelines fail when tests fail, and you're able to see more information about why.

A test failing due to a regression often exposes an engineer to functionality they are not familiar with. The information logged along with the test implementation should provide enough context that they can understand what is being tested and what has gone wrong, and be able to reason about how they can resolve it.

2024-01-04 16:43 UTC, RobJohnson-HO commented on docs/standards/testing.md
> +The intent of any test should be clear as they can provide a form of documentation to the overall solution, they should be relatively easy to understand with coverage tracked, although it must be str
This sentence is clunky and hard to read.  I think the grammar needs fixing.  Suggestion:

The intent of any test should be clear as they can provide a form of documentation to the overall solution.
The tests should be relatively easy to understand with a track of the overall testing coverage kept.  It is good to keep in mind that test coverage of a code base is not a definitive marker of quality.

2024-01-04 16:43 UTC, RobJohnson-HO commented on docs/standards/testing.md
> +A good test should be clear on the intent of the test, should only have one test case, and be readable and the test should pass everytime without changes to the underlying code.
Correcting grammar suggestion:

A good test should be clear on the intent of the test, have one test case, be readable and should pass every time without changes to the underlying code.

2024-01-04 16:43 UTC, RobJohnson-HO commented on docs/standards/testing.md
> +Testing can come in different forms unit/integration/mutation/property based, but all must adhere to the requirements laid out as the following benefits can be achieved from it:
Correcting grammar suggestion:

Testing can come in different forms, unit/integration/mutation/property based, but all must adhere to the requirements as the following benefits can be achieved:

2024-01-04 16:43 UTC, RobJohnson-HO commented on docs/standards/testing.md
> +- Easy to connect failures in code from failed tests
I think this is meant to be correct:

Easy to correct failures in code from failed tests.

2024-01-04 16:43 UTC, RobJohnson-HO commented on docs/standards/testing.md
> +- Tests should be automated when possible
Not sure this should be here as a benefit, it is a requirement.

2024-01-04 16:43 UTC, RobJohnson-HO commented on docs/standards/testing.md
> +- Developers should be able to write and run tests and not silo'd to QAT
Not sure this is a benefit either as it reads like a requirement.  Maybe it could be re-written as:

- Tests are owned by the code owners and not within a silo external to the team.

Happy to be challenged a bit on this one though.  It could probably be a bit more clear.

2024-01-05 08:57 UTC, aaronrussellHO commented on docs/standards/testing.md
> +The intent of any test should be clear as they can provide a form of documentation to the overall solution, they should be relatively easy to understand with coverage tracked, although it must be str
Looks good to me, I'll update

2024-01-05 09:17 UTC, oluashiruHO commented on docs/standards/testing.md
> +The tests should be relatively easy to understand with a track of the overall testing coverage kept. It is good to keep in mind that test coverage of a code base is not a definitive marker of quality
I'll reword this "It is good to keep in mind that test coverage of a code base is not a definitive marker of quality."

To something like: "Strong test coverage of a code base contributes towards overall quality of application code, although it is not necessarily the only definitive marker of quality code depending on your application context."

_i.e We appreciate that it's not all about test coverage depending on your use case, but we don't want to seemingly discourage people from making an effort towards having good coverage where possible._

2024-01-05 09:19 UTC, RobJohnson-HO commented on docs/standards/testing.md
> +The tests should be relatively easy to understand with a track of the overall testing coverage kept. It is good to keep in mind that test coverage of a code base is not a definitive marker of quality
Good points, agreed.

2024-01-05 09:20 UTC, RobJohnson-HO commented on docs/standards/testing.md
> +- Developers should be able to write and run tests and not silo'd to QAT
Agreed looks good.

2024-01-05 09:24 UTC, aaronrussellHO commented on docs/standards/testing.md
> +The tests should be relatively easy to understand with a track of the overall testing coverage kept. It is good to keep in mind that test coverage of a code base is not a definitive marker of quality
Agreed && updated

2024-01-05 09:31 UTC, oluashiruHO commented on docs/standards/testing.md
> +- Developers should be able to write and run tests and not silo'd to QAT
This touches on code ownership, but is code always owned by the same team or by a team? - e.g. more open source projects for instance may not always be owned by a team.

Also, shouldn't this be generally left to a team or project's Ways of Working - i.e who writes what test - within a team or outside? - as I agree that the above point around this is not a benefit of having tests.

_Not sure this should be part of this standard, and instead should be covered by any other standard that caters more of general code ownership - or perhaps a standard/principle that generally covers engineering team dynamics - if there is one._

2024-01-05 09:54 UTC, oluashiruHO commented on docs/standards/testing.md
> +The earlier testing happens in the development process, the less time is spent debugging, the better quality of the code through more tests, and the different paths are considered more. Using TDD can
Consider restructuring to something like this:

```suggestion
Writing tests early and often in a software development process tends to reduce the amount of time spent debugging. Good tests written early generally helps improve the overall assurance and design quality of your application. 
Test Driven Development (TDD) is a valuable development approach that can help towards achieving this. This development approach encourages you to think ahead on how your requirements can be met by thinking on how your solution can be tested first at unit level. Once a test is written first albeit failing due to non-existing solution, you can implement your solution to pass the test, and then refactor. "Testing early and often" in this case leads to "refactoring early and often", which continuously improves the quality of your application code and design.```

2024-01-05 10:00 UTC, oluashiruHO commented on docs/standards/testing.md
> +The ability to repeat the same tests, gives confidence that if there is a failure, something has changed to affect that failure. The values shouldn't change based on enviroments and unit tests should
```suggestion
The ability to repeat the same tests gives confidence that if there is a failure, something has changed to affect that failure. The values that a test rely on shouldn't change based on environments, and tests such as unit tests should not depend on other external factors and dependencies (such as third party API, etc) to run.
```

2024-01-05 10:17 UTC, oluashiruHO commented on docs/standards/testing.md
> +A test failing due to a regression often exposes an engineer to functionality they are not familiar with. The information logged along with the test implementation should provide enough context that
```suggestion
A test failing due to a regression often implies that a functionality has been added that contradict existing (and previous expectations), this should be reviewed to understand why this happened and what needs to be done to fix the regression issue. Although the area of concern may be unfamiliar, the information logged along with the test implementation should provide enough context to help with this review - in understanding what is being tested, what has gone wrong, and hence be able to reason about how the issue can be resolved.
```

2024-01-05 10:22 UTC, oluashiruHO commented on docs/standards/testing.md
> +Testing for all eventualities helps to write code that can handle errors in a better way. This should include things like testing for illegal arguements, or no arguements to be passed.
```suggestion
Testing for all eventualities helps to write code that can handle errors and exceptions. This should include things like testing for illegal or no arguments, dependencies' edge cases (which can often be simulated through mocking dependencies as appropriate).
```

2024-01-05 10:37 UTC, jeff-horton-ho-sas commented on docs/standards/testing.md
> +A test failing due to a regression often exposes an engineer to functionality they are not familiar with. The information logged along with the test implementation should provide enough context that
My intent with this paragraph was to explain why it is important that "Tests MUST have a purpose and explicit result" which is to give context to an engineer interacting with the test and the behaviour it is verifying. It is targetted at the author of the test, so adding notes about how the engineer who sees the failing test should respond confuses things.

2024-01-05 10:42 UTC, jeff-horton-ho-sas commented on docs/standards/developer-testing.md
> +A test failing due to a regression often implies that a functionality has been added that contradict existing (and previous expectations), this should be reviewed to understand why this happened and
```suggestion
A test failing due to a regression often exposes an engineer to parts of the code they are not familiar with. The information logged along with the test implementation should provide enough context that they can understand what is being tested and what has gone wrong, and be able to reason about how they can resolve it.
```
My intent with this paragraph was to explain why it is important that "Tests MUST have a purpose and explicit result" which is to give context to an engineer interacting with the test and the behaviour it is verifying. It is targetted at the author of the test, so adding notes about how the engineer who sees the failing test should respond confuses things.

@oluashiruHO @aaronrussellHO  Happy to be challenged on this, but I don't think we should include the additional wording here. We could potentially add something somewhere else about being responsive to test failures if you feel that needs to be standardised.

2024-01-05 11:31 UTC, oluashiruHO commented on docs/standards/developer-testing.md
> +A test failing due to a regression often implies that a functionality has been added that contradict existing (and previous expectations), this should be reviewed to understand why this happened and
So "a test failing due to regression often exposes an engineer to parts of the code they are not familiar with", isn't always the case - in fact I'd argue it's actually about 50% the case. An engineer can equally easily introduce regression with well-trodden paths - mainly due to complacency and over-confidence. 

My suggestion sets a background to what regression is at a basic level (leaving out assumption that what this means is clear), and that a failure would almost always need to be reviewed regardless of familiarity or not (because the cause of the regression could well have been due to over-familiarity / complacency and assumptions in the first place). 
I then proceed to highlights that it is important the test has all it needs for someone appropriate to be able to review and resolve successfully.

I also tried to remove reference to the word 'engineer' - because this is 'developer testing' doc, and depending on the layer of test being reviewed or context, the reviewer/resolver may not necessarily identify as an engineer, and is instead a 'developer', or neither - so thought to leave out whilst still making the same point.

The main difference I suppose between my view and yours is that, yours tries to cater to providing info and context in test mainly due to lack of familiarity, mine takes an approach that your test should have enough info and context for anyone that's appropriate to review and resolve successfully, regardless of levels familiarity with code base. Whilst also providing some info on the scenario where this would typically apply (regression - and what that is).

2024-01-18 16:48 UTC, jeff-horton-ho-sas approved these changes

2024-01-18 17:10 UTC, oluashiruHO approved these changes

2024-01-19 09:27 UTC, robertdeniszczyc2 requested changes

2024-01-19 09:27 UTC, robertdeniszczyc2 commented on docs/standards/developer-testing.md
> +      items:
Items are missing in Related links. If there are no related links, this can be removed

2024-01-19 09:40 UTC, robertdeniszczyc2 commented on docs/standards/developer-testing.md
> +The tests should be relatively easy to understand with a track of the overall testing coverage kept. Strong test coverage of a code base contributes towards overall quality of application code, altho
Hi, I have a few suggestions around this to consider;

```suggestion
The tests should be easy to understand with a track of the overall testing coverage kept. Strong test coverage of a code base contributes towards overall quality of application code, although depending on your application context, it may not necessarily be the only definitive marker of quality code.
```

As this is a Standard it needs to be assertive. "relatively" is subjective, so we should tend more to the assertive "tests should be easy to understand".

----------

`with a track of the overall testing coverage kept` 

Could this be elaborated on, I'm not sure I fully understand the implementation of this. Where and how should this record be maintained?

2024-01-19 09:42 UTC, robertdeniszczyc2 commented on docs/standards/developer-testing.md
> +Testing can come in different forms, unit/integration/mutation/property based, but all must adhere to the requirements as the following benefits can be achieved:
```suggestion
Testing can come in different forms, for example unit/integration/mutation/property based, but all must adhere to the requirements as the following benefits can be achieved:
```

Added "for example" here, to account for missing types. As this Standard isn't referencing a particular type you could also include performance testing, accessibility testing, security testing, penetration testing, load testing, device testing, etc

2024-01-19 09:44 UTC, robertdeniszczyc2 commented on docs/standards/developer-testing.md
> +Writing tests early and often in a software development process tends to reduce the amount of time spent debugging. Good tests written early generally helps improve the overall assurance and design q
```suggestion
Writing tests early and often in a software development process tends to reduce the amount of time spent debugging. Good tests written early generally helps improve the overall assurance and design quality of your application.
```

"tends to" and "generally" makes this a bit vague. If this is a MUST, we should be explicit in why I should test early and often.

This is also tending towards unit tests, but the Standard is type-agnostic.

2024-01-19 09:46 UTC, robertdeniszczyc2 commented on docs/standards/developer-testing.md
> +Test Driven Development (TDD) is a valuable development approach that can help towards achieving this. This development approach encourages you to think ahead on how your requirements can be met by t
This is more commonly referred to as the Red, Green, Refactor approach

https://www.codecademy.com/article/tdd-red-green-refactor

2024-01-19 09:52 UTC, robertdeniszczyc2 commented on docs/standards/developer-testing.md
> +The ability to repeat the same tests gives confidence that if there is a failure, something has changed to affect that failure. The values that a test rely on shouldn't change based on environments,
```suggestion
The ability to repeat the same tests gives confidence that if there is a failure, something has changed to affect that failure. The values that a test rely on shouldn't change based on environments, and tests such as unit tests should not depend on other external factors and dependencies (for example third party APIs) to run.
```

2024-01-19 09:52 UTC, robertdeniszczyc2 commented on docs/standards/developer-testing.md
> +- Tests are owned by the same team who owns the code and not within a silo external to the team.
```suggestion
- Easy to correct failures in code from failed tests
- Security & confidence when continously integrating code
- Easy to understand intent and functionality of code
- Tests are owned by the same team who owns the code and not within a silo external to the team
```

Grammar correction

2024-01-19 09:55 UTC, robertdeniszczyc2 commented on docs/standards/developer-testing.md
> +One way of doing this is through monitoring test coverage, Test coverage helps a team understand the amount of code that is tested within a codebase. Setting a minimum threshold (such as 80%) ensures
```suggestion
One way of doing this is through monitoring test coverage. Test coverage helps a team understand the amount of code that is tested within a codebase. Setting a minimum threshold (such as 80%) ensures that any new code is tested. Another example is mutation testing.
```

2024-01-19 12:01 UTC, aaronrussellHO commented on docs/standards/developer-testing.md
> +Test Driven Development (TDD) is a valuable development approach that can help towards achieving this. This development approach encourages you to think ahead on how your requirements can be met by t
I've added this to the end of this paragraph, but think it's worth writing a pattern to show this, rather than linking to an article if you're happy with that?

2024-01-19 13:41 UTC, robertdeniszczyc2 approved these changes

2024-01-19 13:42 UTC, merged