chore(351): add service reliability standard
UKHomeOffice/engineering-guidance-and-standards pull request #352
Opened 2023-11-23 14:57 UTC by oluashiruHO

Is this pull request a content or a code change? (Please fill in the relevant section and delete the other)

# Code change
I can confirm:
## Accessibility considerations
- [x] Please review the [accessibility checks for layout changes](https://github.com/UKHomeOffice/engineering-guidance-and-standards/blob/main/technical-docs/accessibility/layout-checks.md).
- [x] This change will not change layouts, page structures or anything else that might impact accessibility

# Content change 
- [x] Please review the [accessibility checks for content changes](https://github.com/UKHomeOffice/engineering-guidance-and-standards/blob/main/technical-docs/accessibility/content-checks.md).

I can confirm:
- [x] Content does not include any code or configuration changes (excluding frontmatter information)
- [x] Content meets the content standards
e.g. [Writing a principle](https://engineering.homeoffice.gov.uk/standards/writing-a-principle/) and [Writing a standard](https://engineering.homeoffice.gov.uk/standards/writing-a-standard/)
- [x] Content is suitable to open source, i.e.:
    - Content does not relate to unreleased gov policy
    - Content does not refer to anti-fraud mechanisms
    - Content does not include sensitive business logic
- [x] Last updated date for content is correct

2023-11-23 16:12 UTC, daniel-ac-martin commented on docs/standards/service-reliability.md
> +Considering the acceptable time it takes for your application to recover (Mean Time To Recover / MTTR), additional headroom is allowed in the event of failures - for example, it is permissible if you
Assuming this lives somewhere, is it worth calling out auto-scaling here?

2023-11-23 16:12 UTC, daniel-ac-martin commented on docs/standards/service-reliability.md
> +Considering the acceptable time it takes for your application to recover (Mean Time To Recover / MTTR), additional headroom is allowed in the event of failures - for example, it is permissible if you
Oh sorry, that's the next section.

2023-11-23 19:31 UTC, daniel-ac-martin commented on docs/standards/service-reliability.md
> +- Check that services respond with appropriate cache directives in HTTP response headers
We often can't allow caching in order to protect our data. I agree we should do it for non-private static assets though. I know you've got 'where possible', but if we open with that is it appropriate to have this as a MUST rather than a SHOULD?

2023-11-23 19:33 UTC, daniel-ac-martin commented on docs/standards/service-reliability.md
> +### Service MUST be able to toletate expected load
```suggestion
### Service MUST be able to tolerate expected load
```

2023-11-23 19:33 UTC, daniel-ac-martin commented on docs/standards/service-reliability.md
> +### Service MUST be able to toletate expected stress
```suggestion
### Service MUST be able to tolerate expected stress
```

2023-11-23 19:33 UTC, daniel-ac-martin commented on docs/standards/service-reliability.md
> +Validate with test teams that the service has been soak tested to expected peak load.
This assumes a separate test team, which I don't think is ideal.

2023-11-23 19:34 UTC, daniel-ac-martin commented on docs/standards/service-reliability.md
> +Validate with test teams that the service has been stress tested to expected peak load.
This assumes a separate test team, which I don't think is ideal.

2023-11-23 19:37 UTC, daniel-ac-martin commented
I wonder whether this is really a single standard. (I defer to others on the definitions we are using.)

To me 'service reliability' is a goal that we are trying to achieve, rather than a specific standard. So I wonder if this should be broken down.

I also think this assumes that every service has a high availability requirement, which isn't really true. If we were to consider a back-end process (no human user), how many of these points remain as MUSTs?

2023-11-29 09:30 UTC, aaronrussellHO commented on docs/standards/service-reliability.md
> +- Check that services respond with appropriate cache directives in HTTP response headers
Yeah, I agree, I think this should call out static assets in particular, and any public endpoints

2023-11-29 09:31 UTC, aaronrussellHO commented on docs/standards/service-reliability.md
> +- Identify and remediate performance bottlenecks in the service and upstream / downstream systems and services.
```suggestion
The service must be stressed tested beyond normal load conditions (at least 200% of expected peak load), so as to;

- Understand how the application behaves beyond normal conditions, and document any findings
- Ensure scaling policies behave as expected, and that normal service can be expected from unexpected load conditions
- Identify and remediate performance bottlenecks in the service and upstream / downstream systems and services.
```

2023-11-29 09:32 UTC, aaronrussellHO commented on docs/standards/service-reliability.md
> +- Understand how the service recovers from high load situations and ensure it relinquishes unused resource back to the underlying infrastructure
```suggestion
### Service MUST be soak tested.

The service must be soak tested to ensure normal operating conditions over time, from low, normal to high load situations, so as to:

- Understand how the service behaves over a period of time, and that garbage collection effectively prevents memory and CPU leaks over time
- Understand how the service recovers from high load situations and ensure it relinquishes unused resource back to the underlying infrastructure
```

2023-11-29 09:35 UTC, aaronrussellHO commented on docs/standards/service-reliability.md
> +Home office systems should be able to withstand failures during various circumstances, both expected and unexpected over a specified period in specified environments.
The end of this sentence seems a little vague? Surely if it's unexpected, it's not over a specified period?

2023-11-29 09:42 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +Home office systems should be able to withstand failures during various circumstances, both expected and unexpected over a specified period in specified environments.
@aaronrussellHO How would you put it otherwise? - (to make the point that systems should be able to cope with all eventualities)

2023-11-29 09:51 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +- Identify and remediate performance bottlenecks in the service and upstream / downstream systems and services.
@aaronrussellHO being a big block of text, it's hard to see, is your suggestion mainly space and line break changes? or am I missing something? - a comment to go with suggested changes would be ideal.

2023-11-29 09:51 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +- Understand how the service recovers from high load situations and ensure it relinquishes unused resource back to the underlying infrastructure
@aaronrussellHO being a big block of text, it's hard to see, is your suggestion mainly space and line break changes? or am I missing something? - a comment to go with suggested changes would be ideal.

2023-11-29 09:51 UTC, aaronrussellHO commented on docs/standards/service-reliability.md
> +- Identify and remediate performance bottlenecks in the service and upstream / downstream systems and services.
Sorry, yes, just line spacing in this one.

2023-11-29 09:52 UTC, aaronrussellHO commented on docs/standards/service-reliability.md
> +- Understand how the service recovers from high load situations and ensure it relinquishes unused resource back to the underlying infrastructure
Same here, just line changes, no text changes

2023-11-29 09:53 UTC, aaronrussellHO commented on docs/standards/service-reliability.md
> +Home office systems should be able to withstand failures during various circumstances, both expected and unexpected over a specified period in specified environments.
```suggestion
Home Office systems should be able to withstand different eventualities, this could include scheduled maintenance, data centre failure and increased load and stress.``

2023-11-29 09:55 UTC, aaronrussellHO commented on docs/standards/service-reliability.md
> +Reliability expectations should be clear and baselined so that Service Level Objectives (SLOs) can be defined for measures that can keep Home Office services reliable.
```suggestion
### Service reliability MUST be observable relative to defined service level expectations

Reliability expectations should be clear and baselined so that Service Level Objectives (SLOs) can be defined for measures that can keep Home Office services reliable.
```
Same here, spacing between heading and body

2023-11-29 13:41 UTC, edhamiltonHO commented on docs/standards/service-reliability.md
> +- [Requirement(s)](#requirements)
Don't need the first line here

```suggestion

```

2023-11-29 14:02 UTC, edhamiltonHO commented on docs/standards/service-reliability.md
> +### Service MUST be sized appropriately for normal operations
I think the spirit of this requirement could be split out to supplement some of the other requirements. 

e.g.
- definition of 'normal operations' probably belongs in first requirement on definition of SLOs, along with regular reviews and setting acceptable mean time to recover
- sizing and scaling are heavily linked - initial sizing choices must enable appropriate scaling strategies for meeting load and cost optimisation (cost optimisation will be a different standard at some point I'd expect)
- assurance of the appropriateness of these things is part of the load, stress and soak testing requirements

2023-11-29 14:08 UTC, edhamiltonHO commented on docs/standards/service-reliability.md
> +Home office systems should be able to withstand failures during various circumstances, both expected and unexpected over a specified period in specified environments.
I don't think we want to lose the essence of the point around failures over a specified period of time. We want people to build reliability to meet sensibly defined expected service levels.

2023-11-29 14:51 UTC, daniel-ac-martin commented on docs/standards/service-reliability.md
> +Home office systems should be able to withstand failures during various circumstances, both expected and unexpected over a specified period in specified environments.
I'm a bit worried that if we focus too much on service levels (SLOs/SLAs?) then they might be so easy to meet that we don't do some of the common sense stuff. (You see this with performance testing, for example.)

I'd think that if we build things to be as reliable as possible, we'll probably find that we far exceed the required service level.

With regards to this paragraph, I'm a little confused as to what it's getting at. Is this about being resilient in the face of any failure modes that can be anticipated? (Which requires taking the time to think about what those failure modes are.)

2023-11-29 15:09 UTC, edhamiltonHO commented on docs/standards/service-reliability.md
> +Home office systems should be able to withstand failures during various circumstances, both expected and unexpected over a specified period in specified environments.
Agree that we don't want to under or over engineer for reliability (though that will always happen to an extent). I think that is why we want to talk a little bit about service levels, to put sensible bounds and direction for what is required, discouraging the unnecessary.

We can probably hold off fully re-writing the opening description for the standard until the requirements are more concrete, the description will usually just summarise the whole. I'd say the intent is for the standard to call out the minimum expectations, that apply for any service at HO, with scope for people to extend dependant on their case.

2023-11-29 17:16 UTC, GraemeSutherlandHO commented on docs/standards/service-reliability.md
> +- Check that services respond with appropriate cache directives in HTTP response headers
think that "appropriate" needs to be made clear here.

2023-12-01 16:35 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +### Service MUST be sized appropriately for normal operations
Following discussion at Service Reliability GUILD

Merged point on sizing with point on autoscaling.

Will resolve this comment, but do feel free to raise another comment on the new status on the PR.

Cheers.

2023-12-01 16:35 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +- Check that services respond with appropriate cache directives in HTTP response headers
Removed requirement altogether from Standard.

2023-12-01 16:36 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +Validate with test teams that the service has been soak tested to expected peak load.
Following discussion at Service Reliability GUILD

Removed line.

2023-12-01 16:36 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +Validate with test teams that the service has been stress tested to expected peak load.
Following discussion at Service Reliability GUILD

Removed line.

2023-12-04 09:57 UTC, robertdeniszczyc2 commented
Hi,

I started providing feedback on this in the PR, but I think a lot of my thoughts are already captured by @daniel-ac-martin above (https://github.com/UKHomeOffice/engineering-guidance-and-standards/pull/352#issuecomment-1824850240).

Service reliability is already mentioned in the [MaC Pattern](https://engineering.homeoffice.gov.uk/patterns/monitoring-as-code/) and I feel some of the MUSTs in this feel closer to a Pattern than a Standard.

I'm happy to talk through in more detail, but I feel this needs some more refinement if it is to be implemented as a Standard.

Thanks,
Rob

2023-12-15 09:51 UTC, LDP0wer reviewed
I've add comments from MBTP perspective. There's some lines in here which were explicitly to support QAT testing these Standards, which we won't need. Also offered rewording suggestions where our original wording was a bit clunky.

2023-12-15 09:51 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +Check that services are spread across multiple nodes and/or multiple availability zones; this can be checked by checking;
Same comment as for the above Standard, I'm not sure we need lines 56-59 as this was originally for QAT testing purposes.

2023-12-15 09:51 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +Although rare, services should consider the possibility and guard against such scenarios by operating from multiple data centres by spreading applications / services across multiple data centres (e.g
"by operating from multiple data centres" feels like a duplicate clause and can probably be removed.

2023-12-15 09:51 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +Check that services are spread across multiple nodes and/or multiple availability zones; this can be checked by checking;
"this can be met with" is a less clunky clause then "this can be checked by checking;"

2023-12-15 09:51 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +- Go through upstream services your service relies on, and  how it reacts to an expected or unexpected failure of that service.
"Feel as if we need another word in there, maybe "Go through upstream services your service relies on, and **test** how it reacts"

2023-12-15 09:51 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +- Tests results for service proving behaviour.
Assumes external test team, could be removed.

2023-12-15 09:51 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +- Check that AWS services are sized appropriately
Do we want to go tech agnostic and just refer to cloud or infrastructure services?

2023-12-15 09:51 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +- Refer to appropriate dashboards to ensure CPU and Memory utilisation.
Should probably be "Refer to appropriate dashboards to ensure CPU and Memory utilisation **are sized appropriately"**

2023-12-15 09:51 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +Ideally, scaling should be based on some metric that is indicative of an application's performance (such as number of busy threads, queue depth) rather than system resources such as CPU and memory as
This wording has always been hard for me to read - I would rephrase to

Ideally, scaling should be based on some metric that is indicative of an application's performance (such as number of busy threads, queue depth) rather than system resources such as CPU and memory. Not scaling based on intelligent metrics could result in situations such as:
- your application has exhausted threads and cannot service any more requests, while CPU and memory utilisation is low 
- a messaging queue has filled up, but there are not enough consumers to process messages

2023-12-22 11:46 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +- AWS Auto Scaling Group configurations
removed checks

2023-12-22 11:47 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +Check that services are spread across multiple nodes and/or multiple availability zones; this can be checked by checking;
removed checks

2023-12-22 11:47 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +Although rare, services should consider the possibility and guard against such scenarios by operating from multiple data centres by spreading applications / services across multiple data centres (e.g
removed checks

2023-12-22 11:47 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +Check that services are spread across multiple nodes and/or multiple availability zones; this can be checked by checking;
removed checks

2023-12-22 11:48 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +- Go through upstream services your service relies on, and  how it reacts to an expected or unexpected failure of that service.
removed checks

2024-01-12 10:53 UTC, LDP0wer reviewed
I've left a few comments on small formatting/grammar suggestions.

2024-01-12 10:53 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +Basing scaling policies based on system resources should be the fallback option, rather than the main criteria by which you scale.
I think 'based' isn't needed in this sentence.

2024-01-12 10:53 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +  - This is particularly important as there will be hidden limits that affect scaling capacity, such as limits on upstream systems, Cloud accounts, or network throughput on appliances connecting to 3
I think there's an extra space at the beginning of this line. I also think that 'appliances' should say 'applications'

2024-01-12 10:53 UTC, LDP0wer commented on docs/standards/service-reliability.md
> +Go through upstream services your service relies on, and test how it reacts to an expected or unexpected failure of that service.
This is more testing guidance, this will probably not be needed.

2024-01-12 14:54 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +Basing scaling policies based on system resources should be the fallback option, rather than the main criteria by which you scale.
```suggestion
Basing scaling policies on system resources should be the fallback option, rather than the main criteria by which you scale.
```

2024-01-12 14:55 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +  - This is particularly important as there will be hidden limits that affect scaling capacity, such as limits on upstream systems, Cloud accounts, or network throughput on appliances connecting to 3
```suggestion
- This is particularly important as there will be hidden limits that affect scaling capacity, such as limits on upstream systems, Cloud accounts, or network throughput on appliances connecting to 3rd parties/POISE.
```

2024-01-12 14:56 UTC, oluashiruHO commented on docs/standards/service-reliability.md
> +Go through upstream services your service relies on, and test how it reacts to an expected or unexpected failure of that service.
```suggestion
```

2024-01-18 12:21 UTC, edhamiltonHO approved these changes

2024-01-19 13:43 UTC, edhamiltonHO requested changes

2024-01-19 13:43 UTC, edhamiltonHO commented on docs/standards/service-reliability.md
> +id: SEGAS-00013
The new developer-testing standards is SEGAS-00013, this will need to be SEGAS-00014 now

2024-01-23 09:25 UTC, edhamiltonHO approved these changes

2024-03-14 15:35 UTC, jeff-horton-ho-sas requested changes
Updates to make content consistent with the GOV.UK style guide, especially:
- https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bullet-points-steps
- https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#capitalisation

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +Reliability expectations should be clear and baselined so that Service Level Objectives (SLOs) can be defined for measures that can keep Home Office services reliable.
```suggestion
Reliability expectations should be clear and baselined so that service level objectives (SLOs) can be defined for measures that can keep Home Office services reliable.
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +Although rare, services should consider the possibility and guard against such scenarios by spreading applications / services across multiple data centres (e.g. Availability Zones) either in Active/A
```suggestion
Although rare, services should consider the possibility and guard against such scenarios by spreading applications / services across multiple data centres (e.g. availability zones) either in active/active or active/passive configuration.
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +In the event of an unexpected event (hardware fault, withdrawal of virtualised hardware e.g. SPOT instances) or an expected event (maintenance activities) your service may suffer an outage.
```suggestion
In the event of an unexpected event (hardware fault, withdrawal of virtualised hardware e.g. spot instances) or an expected event (maintenance activities) your service may suffer an outage.
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +Where required based off business requirements, the service can be load, soak or stressed tested to expected normal conditions as defined by the service volumetrics to;
```suggestion
Where required based off business requirements, the service can be load, soak or stressed tested to expected normal conditions as defined by the service volumetrics to: 
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +The service must be stressed tested beyond normal load conditions (at least 200% of expected peak load), so as to;
```suggestion
The service must be stressed tested beyond normal load conditions (at least 200% of expected peak load), so as to:
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +- attempt to retry within reasonable limits of your service
```suggestion
Your service should guard against such scenarios by:
- handling the failure gracefully
- attempting to reconnect
- attempting to retry within reasonable limits of your service
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +Furthermore, implement a backoff strategy if your transactions allow it.
```suggestion
When retrying transactions, particularly when an upstream service was down, avoid flooding the upstream service(s) with requests thus potentially creating a DDoS style attack on the upstream service, potentially causing further upstream service outages. Furthermore, implement a backoff strategy if your transactions allow it.
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +- Check that services respond accordingly during load and stress testing; usually services should respond with HTTP 503
```suggestion
Check that services respond accordingly during load and stress testing; usually services should respond with HTTP 503
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +- This is particularly important as there will be hidden limits that affect scaling capacity, such as limits on upstream systems, Cloud accounts, or network throughput on appliances connecting to 3rd
```suggestion
- understand how the application behaves beyond normal conditions, and document any findings
- ensure scaling policies behave as expected, and that normal service can be expected from unexpected load conditions
- identify and remediate performance bottlenecks in the service and upstream / downstream systems and services

This is particularly important as there will be hidden limits that affect scaling capacity, such as limits on upstream systems, cloud accounts, or network throughput on appliances connecting to 3rd parties/POISE.
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +- Understand how the service recovers from high load situations and ensure it relinquishes unused resource back to the underlying infrastructure
```suggestion
- understand how the service behaves over a period of time, and that garbage collection effectively prevents memory and CPU leaks over time
- understand how the service recovers from high load situations and ensure it relinquishes unused resource back to the underlying infrastructure
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +Such scenario is more common and your service should guard against such scenarios by operating;
```suggestion
Such scenario is more common and your service should guard against such scenarios by operating:
```

2024-03-14 15:35 UTC, jeff-horton-ho-sas commented on docs/standards/service-reliability.md
> +---
```suggestion
```

2024-04-26 12:40 UTC, jeff-horton-ho-sas approved these changes

2024-04-26 12:44 UTC, edhamiltonHO commented on docs/standards/service-reliability.md
> +date: 2024-01-12
```suggestion
date: 2024-04-26
```

2024-04-26 13:14 UTC, merged