Added guild information onto the engineering website
UKHomeOffice/engineering-guidance-and-standards pull request #422
Opened 2024-05-17 08:15 UTC by aaronrussellHO

Is this pull request a content or a code change? (Please fill in the relevant section and delete the other)

# Code change
I can confirm:
## Accessibility considerations
- [X] Please review the [accessibility checks for layout changes](https://github.com/UKHomeOffice/engineering-guidance-and-standards/blob/main/technical-docs/accessibility/layout-checks.md).

- [X] This change will not change layouts, page structures or anything else that might impact accessibility
- 
# Content change 
- [X] Please review the [accessibility checks for content changes](https://github.com/UKHomeOffice/engineering-guidance-and-standards/blob/main/technical-docs/accessibility/content-checks.md).

I can confirm:
- [X] Content does not include any code or configuration changes (excluding frontmatter information)
- [X] Content meets the content standards
e.g. [Writing a principle](https://engineering.homeoffice.gov.uk/standards/writing-a-principle/) and [Writing a standard](https://engineering.homeoffice.gov.uk/standards/writing-a-standard/)
- [X] Content is suitable to open source, i.e.:
    - Content does not relate to unreleased gov policy
    - Content does not refer to anti-fraud mechanisms
    - Content does not include sensitive business logic

2024-05-17 09:56 UTC, ThomasWilliamsHO commented on docs/about.md
> +The best place to start learning more about the guilds, when they meet and how to join, the best place to start is the Slack.
"is the Slack" that sounds abit weird to me sorry maybe just "is Slack" ?

2024-05-17 10:01 UTC, aaronrussellHO commented on docs/about.md
> +The best place to start learning more about the guilds, when they meet and how to join, the best place to start is the Slack.
I think I was going to say Home Office Slack, but then thought, I'm not sure if it's wider than the Home Office. I'll update.

2024-05-23 08:31 UTC, robertdeniszczyc2 requested changes

2024-05-23 08:31 UTC, robertdeniszczyc2 commented on docs/about.md
> +Bi weekly the various guilds meet to discuss topics relating to their areas and help to contribute towards the guidance, standards and principles on this site.
```suggestion
The guilds meet regularly to discuss topics relating to their areas and contribute towards the guidance, standards and principles.
```

Tweaked wording slightly as not all guilds have the same meeting cadence.

2024-05-23 08:31 UTC, robertdeniszczyc2 commented on docs/about.md
> +### Guild information
```suggestion
### Guild information
On Home Office Slack you'll find more information for each guild in their respective channels along with when they meet, and who to contact to join.
```

I think we can probably expand this section on here to include at least a one-liner for each guild.

2024-05-23 10:11 UTC, aaronrussellHO commented on docs/about.md
> +### Guild information
I've added a sentence under each one and made each guild a heading. Hopefully that's a little more info for each!

2024-05-23 10:41 UTC, jeff-horton-ho-sas commented on docs/about.md
> +
```suggestion
Build, release and deployment guild
: Topics related to the release and deployment pipeline including CI/CD, Feature Toggling and Artefact Management.

  **Slack**: [#segas-build-release-deployment](https://homeoffice.enterprise.slack.com/archives/C02DR9CU4SC)

Low Code
: A space for to discuss low-code engineering guidance and standards.

  **Slack**: [#segas-low-code](https://homeoffice.enterprise.slack.com/archives/C05MK8UM2F7)

Observability
: Topics relating to the ongoing monitoring of applications and services, including Logging, Analytics and Performance.

  **Slack**: [#segas-observability](https://homeoffice.enterprise.slack.com/archives/C02BJSXJ0QK)

Security
: Articles in this section relate to subjects such as Secure Development, Identity & Access and Vulnerability Scanning.

  **Slack**: [#segas-security](https://homeoffice.enterprise.slack.com/archives/C0282A158FM)

Software Design
: Items to be covered to include Frameworks, Languages, Quality and Coding Standards.

  **Slack**: [#segas-software-design](https://homeoffice.enterprise.slack.com/archives/C02AHL4ML7P)

Source Management
: Items to be covered to include Open Source, Licensing and Source Code Management.

  **Slack**: [#segas-source-management](https://homeoffice.enterprise.slack.com/archives/C02DE9B8M25)

Ways of Working
: Items to be covered to include Documentation, Tooling and Defining Stories.

  **Slack**: [#segas-ways-of-working](https://homeoffice.enterprise.slack.com/archives/C02CLUJ01QX)

```

I think this reads better as a summary list.

<img src="https://github.com/UKHomeOffice/engineering-guidance-and-standards/assets/87995501/f4eaf64f-def9-424a-882d-58a30bb21ab5" width="300px"/>
<img src="https://github.com/UKHomeOffice/engineering-guidance-and-standards/assets/87995501/d99d577b-7a39-4162-b7ac-7a7669a5e7e8" width="300px"/>

2024-05-23 10:47 UTC, edhamiltonHO commented on docs/about.md
> +## How we are doing it
I think this section needs to be combined with the 'How we are managing the site' section further down the page. There is a lot of overlapping information.

2024-05-23 10:49 UTC, edhamiltonHO commented on docs/about.md
> +The guilds meet regularly to discuss topics relating to their areas and contribute towards the guidance, standards and principles.
Would be good to introduce what we mean by guilds before this point, it is covered a little bit in the 'why we are doing it' section

2024-05-23 10:51 UTC, edhamiltonHO commented on docs/about.md
> +## How we are doing it
I would suggest that the easiest way to address this comment, and my other one below regarding introducing guilds, would be to move this section to after the 'why we are doing it' section. As long as that doesn't push the useful guild information too far down the page

2024-05-23 10:52 UTC, aaronrussellHO commented on docs/about.md
> +## How we are doing it
Yeah, I think that's why I did it. Maybe I'll review the page as a whole and move things around/change things.

2024-05-23 11:09 UTC, jeff-horton-ho-sas reviewed
* Add links to the tag page for each guild
* Move the Slack: into the link text so that that context is clear when screen readers list all the links on a page.

2024-05-23 11:09 UTC, jeff-horton-ho-sas commented on docs/about.md
> +  **Slack**: [#segas-build-release-deployment](https://homeoffice.enterprise.slack.com/archives/C02DR9CU4SC)
```suggestion
  [**Slack**: #segas-build-release-deployment](https://homeoffice.enterprise.slack.com/archives/C02DR9CU4SC)
  
  [Pages tagged with build, release and deploy](/tags/build-release-and-deploy/)
```

2024-05-23 11:09 UTC, jeff-horton-ho-sas commented on docs/about.md
> +  **Slack**: [#segas-low-code](https://homeoffice.enterprise.slack.com/archives/C05MK8UM2F7)
```suggestion
  [**Slack**: #segas-low-code](https://homeoffice.enterprise.slack.com/archives/C05MK8UM2F7)
  
  [Pages tagged with low code](/tags/low-code/)
```

2024-05-23 11:09 UTC, jeff-horton-ho-sas commented on docs/about.md
> +  **Slack**: [#segas-observability](https://homeoffice.enterprise.slack.com/archives/C02BJSXJ0QK)
```suggestion
  [**Slack**: #segas-observability](https://homeoffice.enterprise.slack.com/archives/C02BJSXJ0QK)
  
  [Pages tagged with observability](/tags/observability/)
```

2024-05-23 11:09 UTC, jeff-horton-ho-sas commented on docs/about.md
> +  **Slack**: [#segas-security](https://homeoffice.enterprise.slack.com/archives/C0282A158FM)
```suggestion
  [**Slack**: #segas-security](https://homeoffice.enterprise.slack.com/archives/C0282A158FM)
  
  [Pages tagged with security](/tags/security/)]
```

2024-05-23 11:09 UTC, jeff-horton-ho-sas commented on docs/about.md
> +  **Slack**: [#segas-software-design](https://homeoffice.enterprise.slack.com/archives/C02AHL4ML7P)
```suggestion
  [**Slack**: #segas-software-design](https://homeoffice.enterprise.slack.com/archives/C02AHL4ML7P)
  
  [Pages tagged with software design](/tags/software-design/)
```

2024-05-23 11:09 UTC, jeff-horton-ho-sas commented on docs/about.md
> +  **Slack**: [#segas-source-management](https://homeoffice.enterprise.slack.com/archives/C02DE9B8M25)
```suggestion
  [**Slack**: #segas-source-management](https://homeoffice.enterprise.slack.com/archives/C02DE9B8M25)
  
  [Pages tagged with source management](/tags/source-management/)
```

2024-05-23 11:09 UTC, jeff-horton-ho-sas commented on docs/about.md
> +  **Slack**: [#segas-ways-of-working](https://homeoffice.enterprise.slack.com/archives/C02CLUJ01QX)
```suggestion
  [**Slack**: #segas-ways-of-working](https://homeoffice.enterprise.slack.com/archives/C02CLUJ01QX)
  
  [Pages tagged with ways of working](/tags/ways-of-working/)
```

2024-05-23 12:54 UTC, aaronrussellHO commented on docs/about.md
> +## How we are doing it
I've moved some stuff around. I've left the info about how we manage the site as that feels different to me. @edhamiltonHO

2024-05-28 08:56 UTC, jeff-horton-ho-sas approved these changes

2024-05-29 12:04 UTC, edhamiltonHO approved these changes

2024-05-29 12:13 UTC, robertdeniszczyc2 approved these changes

2024-05-29 12:20 UTC, merged